аафцацф

diff --git a/.github/workflows/ci_suite.yml b/.github/workflows/ci_suite.yml
--- a/.github/workflows/ci_suite.yml
+++ b/.github/workflows/ci_suite.yml
@@ -67,7 +67,7 @@ jobs:
         id: cache-byond
         uses: actions/cache@v4
         with:
-          path: ${{ env.HOME }}/BYOND-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
+          path: $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
           key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
       - name: Install BYOND
         if: steps.cache-byond.outputs.cache-hit != 'true'
@@ -85,18 +85,26 @@ jobs:
     runs-on: ubuntu-22.04
     steps:
       - uses: actions/checkout@v4
+      - name: Set BYOND_DIR env var
+        run: echo "BYOND_DIR=$HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}" >> $GITHUB_ENV
       - name: Restore Cache
         id: cache-byond
         uses: actions/cache@v4
         with:
-          path: ${{ env.HOME }}/BYOND-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
+          path: $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
           key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
+      - name: Debug List installed BYOND contents123
+        run: ls -R $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR} || echo "Directory not found"
       - name: Install BYOND
         if: steps.cache-byond.outputs.cache-hit != 'true'
         run:  bash scripts/install-byond.sh
+      - name: Debug List installed BYOND contents123321313
+        run: ls -R $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR} || echo "Directory not found"
       - name: "Compile Everything"
         env:
           TEST: COMPILE
         run: |
           source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
           bash test/run-test.sh
+      - name: Debug List installed BYOND contents231321321312312321
+        run: ls -R $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR} || echo "Directory not found"
