111

diff --git a/.github/workflows/ci_suite.yml b/.github/workflows/ci_suite.yml
--- a/.github/workflows/ci_suite.yml
+++ b/.github/workflows/ci_suite.yml
@@ -91,12 +91,18 @@ jobs:
         with:
           path: $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
           key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
+      - name: Debug: List installed BYOND contents
+        run: ls -R $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR} || echo "Directory not found"
       - name: Install BYOND
         if: steps.cache-byond.outputs.cache-hit != 'true'
         run:  bash scripts/install-byond.sh
+      - name: Debug: List installed BYOND contents
+        run: ls -R $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR} || echo "Directory not found"
       - name: "Compile Everything"
         env:
           TEST: COMPILE
         run: |
           source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
           bash test/run-test.sh
+      - name: Debug: List installed BYOND contents
+        run: ls -R $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR} || echo "Directory not found"
